# (c) https://github.com/MontiCore/monticore  

image: maven:3-jdk-8


masterJob:
  script: "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean deploy --settings settings.xml"
  only:
  - master
  - dev
  
BranchJob:
  script: "mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml"
  except:
  - master
  - dev
  
license_management:
  image:
    name: "registry.gitlab.com/gitlab-org/security-products/license-management:11-6-stable"
    entrypoint: [""]
  stage: test
  variables:
    SETUP_CMD: mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B  clean install --settings settings.xml -DskipTests -DargLine="-version:'1.8'"
  allow_failure: true
  script:
    - /run.sh analyze .
  artifacts:
    reports:
      license_management: gl-license-management-report.json
